apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.alauda.io/bind: '[{"container_port":8888,"protocol":"tcp","name":"{{NGINX}}","port":18888}]'
  labels:
    service.alauda.io/name: hivehue
  name: hivehue
  namespace: {{REGION}}
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    component: hivehue
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hivehue
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hivehue
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: hivehue
        component: hivehue
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        name: hue
        image: {{REGISTRY}}/hue:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "4G"
      nodeSelector:
        hivehue: "hue"
