apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.alauda.io/bind: '[{"container_port":3306,"protocol":"tcp","name":"{{NGINX}}","port":13306}]'
  labels:
    service.alauda.io/name: hadoopmysql
  name: hadoopmysql
  namespace: {{REGION}}
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    component: hadoopmysql
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hadoopmysql
  namespace: {{REGION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hadoopmysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service.alauda.io/name: hadoopmysql
        component: hadoopmysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        name: hadoopmysql
        image: {{REGISTRY}}/mysql:5.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: "2G"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: "hive-mysql"
            readOnly: false
      volumes:
        - hostPath:
            path: /alauda_data/hive_mysql
            type: Directory
          name: "hive-mysql"
      nodeSelector:
        hadoopmysql: "mysql"
